# Programming-for-Data-Analysis

## Task 1 : Explain the overall purpose of the package

_NumPy, short for Numerical Python, is a Python library. It is a fundamental Python package that is used for scientific 
computing.  According to (Docs.scipy.org, 2019), “NumPy provides a multidimensional array object, various derived objects 
(such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, 
logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical 
operations, random simulation and much more”. Bacially what this means is that NumPy is very fast dealing with numbers that are in list or multidimensional arrays (lists within lists). We can think of an array as a collection of elements that are of the same 
type and can store one of more values within a single variable. NumPy when used with packages such as Pandas and 
Matplotlib also us to visually see graph and statistics._


_With regards to numpy.random, this is a sub-package of numpy package in Python. While working with simulations the ability 
to generate random numbers is required. According to (Subscription.packtpub.com, 2019) “It uses a particular algorithm, 
called the Mersenne Twister, to generate pseudorandom numbers”. When we think of the word random we would assume that the data that is generated would be completely random but with Python this is not the case in the scientific sense of the word as a pseudorandom number generator (PRNG) is essentially an algorithm for generating seemingly random but still reproducible data._  


## Task 2 : Explain the use of the “Simple random data” and “Permutations” functions

#### Task 2.1 : Explain the use of “Simple random data” 

Simple random sample  can be defined as a subset of a statistical population where of its members has equal probability to be chosen. Simple random data will generate random values that depend on the function selected. The main functions for Random Sampling is uniform, uniform sample, discrete uniform, continuous uniform and standard normal distributions. 

#### numpy.random uses many different functions that I will explain below.

In [2]:
# Import the libaries needed 

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# Example of simply random data using numpy.random.rand using different array sizes

'''
numpy.random.rand (d0, d1, …, dn)

    * Generates an array of a specified shape and fills the shape with random values
    * Uses uniform distribution over
    * A uniform distribution is one in which all values are equally likely with the set range. For example, a distribution 
      from zero to ten, the values from 2 to 3 have a 10% probability as do values from 3 to 5.
'''

# 1D Array 
print("1D Array\n",np.random.rand(3),"\n")

# 2D Array
# Output an array that has an array within it.
print("2D Array\n",np.random.rand(3,6),"\n")

# 3D Array
# Output an array that is an array of arrays of arrays.
print("3D Array\n",np.random.rand(3,2,7),"\n")


1D Array
 [0.85531002 0.3212882  0.91540102] 

2D Array
 [[0.67227242 0.72560473 0.73174079 0.11539582 0.22511399 0.05897818]
 [0.99493269 0.80830478 0.42501824 0.8726226  0.64859349 0.28329596]
 [0.24535985 0.04781701 0.51577799 0.97250586 0.43661545 0.83388953]] 

3D Array
 [[[0.57141006 0.90278408 0.94497934 0.15275359 0.11419045 0.64857129
   0.76285861]
  [0.51664748 0.07316302 0.90557968 0.37186584 0.75778953 0.35259495
   0.73162671]]

 [[0.68248704 0.99203567 0.29210732 0.13231618 0.95280483 0.38287089
   0.36999572]
  [0.49074509 0.89172815 0.34852973 0.56599558 0.57403194 0.97626987
   0.5339244 ]]

 [[0.85523151 0.39437757 0.97844417 0.83276988 0.80980267 0.30733181
   0.28873051]
  [0.96747067 0.95119936 0.56020771 0.97289675 0.49587041 0.45575476
   0.20096123]]] 



In [17]:
'''
numpy.random.randn(d0, d1, ..., dn)

    * Generates an array of a specified shape and fills the shape with random values 
    * Uses normal distribution.
    * A normal distribution is when vales cluster around the average
    * Possible to manipulate array.
'''

# 1D Array 
randn_array1D = np.random.randn(3)
print("1D Array\n",randn_array1D,"\n")

# 2D Array
# Output an array that has an array within it.
randn_array2D = np.random.randn(3,4)
print("2D Array\n",randn_array2D,"\n")
 
# 3D Array
# Output an array that is an array of arrays of arrays.
randn_array3D = np.random.randn(3,4,3)
print("3D Array\n",randn_array3D,"\n")


# Manipulation of 2D array

# 2D Array
randn_array2D = np.random.randn(3,4)
print("2D Array\n",randn_array2D,"\n")
       
# Dividing values with 2. Adding, subtracting and dividing following a similar format. 
print("\nArray * 2 : \n", randn_array2D *2)

#  Find array2d ** 2. 
print("\nArray ** 2 : \n", randn_array2D **2)

 

1D Array
 [ 1.55599822 -1.98990254  1.28828818] 

2D Array
 [[-0.18387604  0.49899495 -1.7805606   0.56289541]
 [-1.23887399  1.18920897 -0.86047912  2.63170968]
 [ 1.02385358  0.25198523  0.73939129  0.10949691]] 

3D Array
 [[[ 1.16915144  0.58267728  0.17822375]
  [ 1.28101214  0.6938999   1.52372246]
  [ 1.28484597 -1.93891131 -1.78409973]
  [-1.59050659  2.09518703  0.59848767]]

 [[ 0.9040978  -0.12216741  0.67925247]
  [-0.14756392 -0.50288562 -1.22752065]
  [ 0.59232645 -0.93407091 -0.63527156]
  [ 1.41574592 -0.81608632  0.31610819]]

 [[ 0.7032795   0.26296413 -0.25759352]
  [-0.17224584  0.54515399  0.85353413]
  [ 0.16124801  0.44235747 -3.31693729]
  [ 0.03770933 -0.16708245  0.89107867]]] 

2D Array
 [[-0.87630048 -0.78616508 -0.41223508  1.40813623]
 [-0.07024508 -0.13191561 -0.80368512  1.20664318]
 [ 2.02429865 -0.58964005 -1.06985707  0.84030285]] 


Array * 2 : 
 [[-1.75260097 -1.57233015 -0.82447017  2.81627246]
 [-0.14049016 -0.26383122 -1.60737024  2.41328637]
 [ 

In [15]:
'''
numpy.random.randint(low, high=None, size=None, dtype='l')

    * Generates and returns random integers. The returned array will be fitter with random numbers from low(inclusive) to 
      high (exclusive).
    * The default value for dtype is np.int.

'''

# 1D Array
# Lowest number will be and including 2 , highest number upto not including 6, 9 values will be displayed in the array
randint_array1D = np.random.randint(low = 2, high = 6, size = 9) 
print ("1D Array:\n",randint_array1D, "\n")  

# 2D Array
# Output an array that has an array within it. 
randint_array2D = np.random.randint(low = 2, high = 6, size = (9, 3))
print ("2D Array:\n",randint_array2D, "\n") 

# 3D Array
# Output an array that is an array of arrays of arrays.
randint_array3D = np.random.randint(low = 2, high = 6, size = (9, 3, 2))
print ("3D Array:\n",randint_array3D, "\n") 


1D Array:
 [4 2 4 3 3 2 5 4 2] 

2D Array:
 [[2 3 4]
 [2 4 5]
 [4 5 4]
 [2 3 2]
 [4 4 5]
 [2 5 5]
 [3 5 2]
 [5 5 2]
 [4 4 5]] 

3D Array:
 [[[5 5]
  [5 2]
  [2 5]]

 [[4 2]
  [2 4]
  [4 4]]

 [[2 4]
  [4 3]
  [5 5]]

 [[4 5]
  [2 4]
  [2 4]]

 [[3 2]
  [2 5]
  [3 2]]

 [[3 4]
  [3 3]
  [3 2]]

 [[2 3]
  [5 4]
  [4 2]]

 [[4 2]
  [2 5]
  [3 2]]

 [[4 5]
  [4 2]
  [2 2]]] 



In [19]:
'''
numpy.random.random_integers(low, high=None, size=None)
    
    * Please note that this function has been deprecated and tge recommendation is to use randint.
    * Generates and returns an array of specified shape and fills it with random integers from low (inclusive) to 
      high (exclusive)
'''

# 1D Array
# Lowest number will be and including 2 , highest number upto not including 6, 9 values will be displayed in the array
random_integers_array1D = np.random.random_integers(low = 2, high = 6, size = 9) 
print ("1D Array:\n",random_integers_array1D, "\n")  

# 2D Array
# Output an array that has an array within it.
random_integers_array2D = np.random.random_integers(low = 2, high = 6, size = (9, 3))
print ("2D Array:\n",random_integers_array2D, "\n") 

# 3D Array
# Output an array that is an array of arrays of arrays.
random_integers_array3D = np.random.random_integers(low = 2, high = 6, size = (9, 3, 2))
print ("3D Array:\n",random_integers_array3D, "\n") 


1D Array:
 [6 2 2 2 5 4 3 3 6] 

2D Array:
 [[5 3 3]
 [5 2 5]
 [5 2 5]
 [2 6 4]
 [3 2 4]
 [6 6 2]
 [4 4 4]
 [3 4 4]
 [3 6 5]] 

3D Array:
 [[[6 6]
  [2 4]
  [2 6]]

 [[5 4]
  [6 5]
  [6 5]]

 [[2 5]
  [6 3]
  [2 2]]

 [[2 3]
  [4 5]
  [2 3]]

 [[5 4]
  [6 6]
  [4 6]]

 [[2 2]
  [5 3]
  [5 5]]

 [[5 3]
  [4 6]
  [2 3]]

 [[3 5]
  [2 3]
  [3 6]]

 [[4 4]
  [4 6]
  [3 6]]] 



C:\Users\richa\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: This function is deprecated. Please call randint(2, 6 + 1) instead
  # Remove the CWD from sys.path while we load stuff.
C:\Users\richa\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: This function is deprecated. Please call randint(2, 6 + 1) instead
  from ipykernel import kernelapp as app
C:\Users\richa\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: This function is deprecated. Please call randint(2, 6 + 1) instead


In [7]:
'''
numpy.random.random_sample(size=None)

    * A function for random sampling in numpy. The function will return an array and fill it with random floats.
    * The results will be in from a continuous uniform distribution over the stated interval.
'''

# 1D Array
# Output random Float number
random_sample_array1D = np.random.random_sample()
print ("1D Array:\n",random_sample_array1D, "\n")

# 2D Array
# Output an array that has an array within it.
random_sample_array2D = np.random.random_sample(size =(1, 3))
print ("2D Array:\n",random_sample_array2D, "\n") 

# 3D Array
# Output an array that is an array of arrays of arrays.
random_sample_array3D = np.random.random_sample((3, 2, 1))
print ("3D Array:\n",random_sample_array3D, "\n") 

1D Array:
 0.013135238893169698 

2D Array:
 [[0.38396348 0.66494726 0.30694328]] 

3D Array:
 [[[0.70036872]
  [0.56895566]]

 [[0.2689658 ]
  [0.31166574]]

 [[0.51269568]
  [0.05224304]]] 



In [8]:
'''
numpy.random.random(size=None)

    * Also function for doing random sampling.
    * The results will be in from a continuous uniform distribution over the stated interval.
'''

# 1D Array
# Output five random Float numbers
random_random_array1D = np.random.random(size = 5)
print ("1D Array:\n",random_random_array1D, "\n")

# 2D Array
# Output an array that has an array within it.
random_random_array2D = np.random.random(size =(2, 4))
print ("2D Array:\n",random_random_array2D, "\n") 

# 3D Array
# Output an array that is an array of arrays of arrays.
random_random_array3D = np.random.random((2, 4, 2))
print ("3D Array:\n",random_random_array3D, "\n") 


1D Array:
 [0.64826006 0.29349483 0.09758882 0.63041712 0.47745336] 

2D Array:
 [[0.98222037 0.57648457 0.34481181 0.41937175]
 [0.11081919 0.9973942  0.73350412 0.12229079]] 

3D Array:
 [[[0.51454328 0.958842  ]
  [0.93228703 0.25001972]
  [0.68623068 0.99782124]
  [0.17675364 0.44720207]]

 [[0.48271877 0.04700128]
  [0.00520824 0.24900005]
  [0.01126909 0.0936016 ]
  [0.99775455 0.19306593]]] 



In [9]:
''''
numpy.random.ranf(size=None)

    * Also function for doing random sampling.
    * The results will be in from a continuous uniform distribution over the stated interval.
'''


# 1D Array
# Output random Float number
random_ranf_array1D = np.random.ranf()
print ("1D Array:\n",random_ranf_array1D, "\n")

# 2D Array
# Output an array that has an array within it.
random_ranf_array2D = np.random.ranf(size =(2, 4))
print ("2D Array:\n",random_ranf_array2D, "\n") 

# 3D Array
# Output an array that is an array of arrays of arrays.
random_ranf_array3D = np.random.ranf((2, 4, 2))
print ("3D Array:\n",random_ranf_array3D, "\n") 

1D Array:
 0.43140692496729505 

2D Array:
 [[0.71419495 0.6443541  0.21343975 0.20837545]
 [0.12784794 0.2479147  0.85927527 0.51673845]] 

3D Array:
 [[[0.07288882 0.70988098]
  [0.87243012 0.26068636]
  [0.88400776 0.68603929]
  [0.33404477 0.6672358 ]]

 [[0.3793639  0.64075767]
  [0.80684944 0.28005429]
  [0.93555432 0.91058616]
  [0.42486811 0.41715325]]] 



In [10]:
'''
numpy.random.sample(size=None)

    * Also function for doing random sampling .
    * The results will be in from a continuous uniform distribution over the stated interval.
'''

# 1D Array
# Output five random Float numbers
random_random_sample_array1D = np.random.sample(size = 5)
print ("1D Array:\n",random_random_sample_array1D, "\n")

# 2D Array
# Output an array that has an array within it.
random_random_sample_array2D = np.random.sample(size =(2, 4))
print ("2D Array:\n",random_random_sample_array2D, "\n") 

# 3D Array
# Output an array that is an array of arrays of arrays.
random_random_sample_array3D = np.random.sample((2, 4, 2))
print ("3D Array:\n",random_random_sample_array3D, "\n") 


1D Array:
 [0.06161867 0.65955043 0.4737295  0.34030089 0.61930466] 

2D Array:
 [[0.28470539 0.97374785 0.41147647 0.58924544]
 [0.9593707  0.63722784 0.61335833 0.80132098]] 

3D Array:
 [[[0.50365445 0.62077963]
  [0.01951436 0.75473008]
  [0.46894315 0.29460186]
  [0.18700598 0.14161526]]

 [[0.18452963 0.59980519]
  [0.24419613 0.94016333]
  [0.95311121 0.08198031]
  [0.78730994 0.11075775]]] 



In [30]:
'''
numpy.random.choice(a, size=None, replace=True, p=None)

    * Generates a random sample from a given 1-D array
    * This can be used when selecting a random password from a list or selecting a random item, 
'''

# Display a non-uniform random sample
print(np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0]))

# Use replacement
print(np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0]))


[2 3 2]
[3 2 0]


In [12]:
'''
numpy.random.bytes(length)

    * Return a random binary string
'''

# Print ramdon bytes
print("Random bytes: ", np.random.bytes(10))

Random bytes:  b'\xf9l\xa7\x95\xe0\xad\xc9\xd6\x8f}'


### Task 2.2 : Explain the use of “Permutations” functions

A permutation function will arrange a list or series of numbers. This function can also be used to change the order in a given list. The two main functions are permutation and shuffle which I will demonstrate below with examples. 

random.shuffle will shuffle the array along the first axis of a multi-dimensional array while the order any sub-arrays will be changed and their contents will stay the same.

random.permutation on the other hand works differently. If the input is integer it will randomly permute np.arange(x) while if the input is an array it will make a copy and shuffle the elements randomly.

In [13]:
'''
numpy.random.shuffle(x)

    * Modify a sequence in-place by shuffling its contents.
    * Shuffle the array along the first axis of a multi-dimensional array while the order any sub-arrays will be changed 
      and their contents will stay the same.
'''

# Shuffle can be used in differenrt deimensions. 
a1 = np.array([100, 5, 1, 2, 3,3,2,8,10])
np.random.shuffle(a1)
print("Shuffle 1D",a1, "\n")

# Shuffle can be used in differenrt deimensions. 
a3 = np.array([[100,5,1,2,3] , [9,4,23,200], [2,5,6,1,300]])
np.random.shuffle(a3)
print("Shuffle 3D",a3,"\n")

# The shuffle can also be reshaped. I have reshaped a1 as it has 9 digits and the reshape is will 3,3 
a3 = a1.reshape(3,3)
print("Reshape 1D \n",a3,"\n")

Shuffle 1D [  2   1   8   5 100   3  10   2   3] 

Shuffle 3D [list([2, 5, 6, 1, 300]) list([100, 5, 1, 2, 3]) list([9, 4, 23, 200])] 

Reshape 1D 
 [[  2   1   8]
 [  5 100   3]
 [ 10   2   3]] 



In [14]:
'''
numpy.random.permutation(x)

    * Randomly permute a sequence, or return a permuted range.
'''

# Generate random ordered an array using permutation.
print("Array from 0  9 :\n",np.random.permutation(10),"\n")

# Permute an array.
print("Permute arrays :\n",np.random.permutation ([[100,5,1,2,3] , [9,4,23,200], [2,5,6,1,300]]),"\n")

# Permute an array
print("Permute arrays :\n",np.random.permutation(['Hello', 'World', 'Richard', 'Feeney', 'Here']))


Array from 0  9 :
 [1 6 5 9 4 2 7 0 3 8] 

Permute arrays :
 [list([9, 4, 23, 200]) list([2, 5, 6, 1, 300]) list([100, 5, 1, 2, 3])] 

Permute arrays :
 ['World' 'Hello' 'Here' 'Richard' 'Feeney']
